/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paint;

import sm.rrn.iu.LienzoImagen2D;

/**
 * Clase que define una Ventana Interna en la cual habrá un Lienzo
 * @author Raul Ruano Narvaez
 */
public class VentanaInterna extends javax.swing.JInternalFrame {
    static int numeroVentana = 1;
    VentanaPrincipal ventanaPrincipal;
    
    /**
     * Creates new form VentanaInterna
     */
    public VentanaInterna() {
        initComponents();
        this.setTitle("Nueva ventana " + numeroVentana++);
        this.setClosable(true);
        this.setMaximizable(true);
        this.setResizable(true);
        this.setIconifiable(true);
    }
    
    /**
    * Constructor por parámetros que asocia una VentanaInterna con su padre VentanaPrincipal
    */
    public VentanaInterna(VentanaPrincipal ventanaPrincipal){
        this();
        this.ventanaPrincipal = ventanaPrincipal;
    }

    /**
    * Devuelve el LienzoImagen2D asociado a la VentanaInterna
    */
    public LienzoImagen2D getLienzo() {
        return lienzo;
    }

    /**
    * Método para setear el LienzoImagen2D a la VentanaInterna
    */
    public void setLienzo(LienzoImagen2D lienzo) {
        this.lienzo = lienzo;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo = new sm.rrn.iu.LienzoImagen2D();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        ventanaPrincipal.updateButtons(this);
        /*if(lienzo.getModoPintado()==ModoPintado.Edicion){
            VentanaPrincipal.setBotonesEdicion(lienzo.getFigura_seleccionada(), lienzo);
        }else{
            VentanaPrincipal.setBotones(lienzo);
        }*/
            
    }//GEN-LAST:event_formInternalFrameActivated

    private void lienzoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseClicked
        // TODO add your handling code here:
        ventanaPrincipal.updateButtons(this);
        /*if(lienzo.getModoPintado()==ModoPintado.Edicion){
            VentanaPrincipal.setBotonesEdicion(lienzo.getFigura_seleccionada(), lienzo);
        }else{
            VentanaPrincipal.setBotones(lienzo);
        }*/
    }//GEN-LAST:event_lienzoMouseClicked

    private void lienzoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseMoved
        // TODO add your handling code here:
        ventanaPrincipal.updateButtons(this);
        /*if(lienzo.getModoPintado()==ModoPintado.Edicion){
            //VentanaPrincipal.setBotonesEdicion(lienzo.getFigura_seleccionada(), lienzo);
        }else{
            //VentanaPrincipal.setBotones(lienzo);
        }*/
    }//GEN-LAST:event_lienzoMouseMoved

    private void lienzoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMousePressed
        // TODO add your handling code here:
        ventanaPrincipal.updateButtons(this);
        /*if(lienzo.getModoPintado()==ModoPintado.Edicion){
            VentanaPrincipal.setBotonesEdicion(lienzo.getFigura_seleccionada(), lienzo);
        }else{
            VentanaPrincipal.setBotones(lienzo);
        }*/
    }//GEN-LAST:event_lienzoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private sm.rrn.iu.LienzoImagen2D lienzo;
    // End of variables declaration//GEN-END:variables
}
