/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm.rrn.iu;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Stroke;
import java.awt.image.BufferedImage;
import sm.rrn.graficos.RectanguloRRN;
import sm.rrn.graficos.RellenoRRN;
import sm.rrn.graficos.ShapeRRN;
import sm.rrn.graficos.TrazoRRN;

/**
 *
 * @author Raúl Ruano Narváez
 */
public class LienzoImagen2D extends Lienzo2D {
    BufferedImage imagen;
    Boolean imagenAbierta;

    /**
     *
     */
    public static Boolean activarBound;
    
    /**
     * Creates new form LienzoImagen2D
     */
    public LienzoImagen2D() {
        initComponents();
        imagen = null;
        imagenAbierta = false;
        activarBound = true;
    }
    
    /**
     *
     * @param imagen
     */
    public void setImage(BufferedImage imagen){
        this.imagen = imagen;
        if(imagen!=null) {
            imagenAbierta = true;
            setPreferredSize(new Dimension(imagen.getWidth(),imagen.getHeight()));
        } 
    }
    
    /**
     *
     * @param guardar
     * @return
     */
    public BufferedImage getImage(boolean guardar){
        if(guardar){
            BufferedImage imageFinal = new BufferedImage(imagen.getWidth(), imagen.getHeight(), imagen.getType());
            activarBound=false;
            paint(imageFinal.createGraphics());
            activarBound=true;
            return imageFinal;
        }
        return imagen;
    }

    /**
     *
     * @return
     */
    public Boolean getImagenAbierta() {
        return imagenAbierta;
    }

    /**
     *
     * @param imagenAbierta
     */
    public void setImagenAbierta(Boolean imagenAbierta) {
        this.imagenAbierta = imagenAbierta;
    }

    /**
     *
     * @return
     */
    public Boolean getActivarBound() {
        return activarBound;
    }

    /**
     *
     * @param activarBound
     */
    public void setActivarBound(Boolean activarBound) {
        this.activarBound = activarBound;
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        
        if(this.imagen!=null) 
            g.drawImage(this.imagen,0,0,this);
        
        dibujarLienzo(g);
    }
    
    /**
     *
     * @param g
     */
    public void dibujarLienzo(Graphics g){
        ShapeRRN shape = new RectanguloRRN(new Point(0,0), imagen.getWidth(), imagen.getHeight());
        Graphics2D g2d = (Graphics2D)g;
                
        if(!imagenAbierta){
            shape.añadirAtributo(new RellenoRRN(shape, true, Color.WHITE));
        }
        
        if(activarBound){
            shape.añadirAtributo(new TrazoRRN(shape, Color.BLACK, TipoTrazo.LINEA_DISCONTINUA, 1)); 
        }
        
        shape.drawShape(g2d, ModoPintado.Rectangulo, null);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(210, 210, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
